export const BASE_URL = "http://localhost:5000";
export const TEST_URL = BASE_URL + "/index/";
export const SCHEDULE_URL = BASE_URL + "/schedule";
export const NAME_FILTER_SCHEDULE_URL = SCHEDULE_URL + "/nameFilter";
export const PROTOTYPE_SCHEDULE_URL = NAME_FILTER_SCHEDULE_URL + "/prototype";
export const CONTRACT_URL= BASE_URL + "/contract";
const ADD_STRING = "/add";
export const ADD_CONTRACT_URL = CONTRACT_URL + ADD_STRING;
export const SHIFT_URL= BASE_URL + "/shift";
const FETCH_NAMES="/fetchAllNames";
const FETCH_ALL = "/fetchAll";
const FETCH_BY_NAME = "/fetchByName";
const REMOVE = "/remove";
export const FETCH_SHIFT_NAMES = SHIFT_URL + FETCH_NAMES;
export const SHIFT_GROUP_URL = BASE_URL + "/shiftGroup";
export const FETCH_SHIFT_GROUP_NAMES = SHIFT_GROUP_URL + FETCH_NAMES;
export const SHIFT_TYPE_URL = BASE_URL + "/shiftType";
export const FETCH_SHIFT_TYPE_NAMES = SHIFT_TYPE_URL + FETCH_NAMES;
export const FETCH_CONTRACT_NAMES = CONTRACT_URL + FETCH_NAMES;
export const USER_URL = BASE_URL + "/user";
export const LOGIN_URL = USER_URL + "/login";
export const LOGOUT_URL = USER_URL + "/logout"
export const SKILLS_URL = BASE_URL + "/skill";
export const FETCH_SKILLS = SHIFT_URL + FETCH_ALL;
const UPDATE= "/update"
export const UPDATE_CONTRACT_URL = CONTRACT_URL + UPDATE;
export const FETCH_CONTRACT_BY_NAME = CONTRACT_URL + FETCH_BY_NAME;
export const DELETE_CONTRACT = CONTRACT_URL + REMOVE;