export const NOTIFICATION_UPDATE = "notification_update"
export const UNSUBSCRIBE_SCHEDULE_STATUS_NOTIFICATIONS = "leave_notification"
export const SUBSCRIBE_SCHEDULE_STATUS_NOTIFICATIONS = "join_notification"
export const VISUALISATION_SUBSCRIPTION = "join_visualisation"
export const VISUALISATION_UNSUBSCRIPTION = "leave_visualisation"
export const VISUALISATION_UPDATE = "update_visualisation"