nurse_name = "name"
nurse_contracts = "contracts"
nurse_id = "nurse_id"

assignment_date = "date"
assignment_employee_name = "employee_name"
assignment_shift = "shift"
assignment_skill = "skill"
schedule_string = "schedule"
end_date = "endDate"
start_date = "startDate"
assignments_string = "assignments"
