FROM node:20

RUN apt-get update && apt-get install -y nginx curl

WORKDIR /app

# install packages
COPY ./*.json .
RUN cd /app && npm i @angular/cli && npm ci

# copy sources
COPY ./src/ ./src/
COPY ./nginx/ /etc/nginx/
COPY ./nginx/sites-available/default-dev /etc/nginx/sites-available/default

EXPOSE 80 443 4200

CMD ["npm", "start"]
